# -*- coding: utf-8 -*-
"""DolaresAColonesRN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JY2WHclU6eTC2LosbGjAt7v3nK_B-dbs
"""

import tensorflow as tf
import numpy as np

Dolares =np.array([1,10,100,30,400,22,38], dtype=float)
Colones =np.array([534.54,5345.45,53454.46,16036.34,213817.84,11759.98,20312.69], dtype=float)

capa1 =tf.keras.layers.Dense(units=3, input_shape=[1])
capa2 =tf.keras.layers.Dense(units=3)
salida =tf.keras.layers.Dense(units=1)
modelo=tf.keras.Sequential([capa1,capa2,salida])

modelo.compile(
    optimizer=tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

print("Comenzado entrenamiento...")
historial=modelo.fit(Dolares,Colones,epochs=10000,verbose=False);
print("Modelo entrenado!")

import matplotlib.pyplot as plt
plt.xlabel("a Epoca")
plt.ylabel("Magnitud de perdida")
plt.plot(historial.history["loss"])
plt.show() 

print("Hagamos una prediccion!")
resultado=modelo.predict([500])
print("El resulta es "+str(resultado)+"en colones")

print("Variable internas de modelo")
print(capa1.get_weights())
print("Variable internas de modelo")
print(capa2.get_weights())
print("Variable internas de modelo")
print(salida.get_weights())